/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: e87521cd3d63d530cf756dc4a59e5d3435bf26db */

static void register_rasterize_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("RASTER_NON_ZERO", RASTER_NON_ZERO, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("RASTER_EVEN_ODD", RASTER_EVEN_ODD, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("RASTER_SPAN_BYTES", RASTER_SPAN_BYTES, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("RASTER_SAMPLES", RASTER_SAMPLES, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("RASTER_LIMIT", RASTER_LIMIT, CONST_PERSISTENT);
}
